# -*- coding: utf-8 -*-
"""E-2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_jJZWZM8qGhhUSEPZ4KrL4lr59w50AzJ
"""

import cv2
import matplotlib.pyplot as plt
from google.colab import files

# Upload image
f = files.upload()
img = cv2.imread(list(f.keys())[0])

# Convert representations
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
_, binary = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)

# Edge detection
edge_gray = cv2.Canny(gray, 100, 200)
edge_binary = cv2.Canny(binary, 100, 200)

# Feature extraction using contours
contours, _ = cv2.findContours(
    binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE
)

# Display results
images = [cv2.cvtColor(img, cv2.COLOR_BGR2RGB),
          gray, binary, edge_gray, edge_binary]

titles = ["Original RGB", "Grayscale", "Binary",
          "Grayscale Edges", "Binary Edges"]

plt.figure(figsize=(12, 7))

for i in range(5):
    plt.subplot(2, 3, i+1)
    plt.imshow(images[i], cmap='gray')
    plt.title(titles[i])
    plt.axis("off")

plt.tight_layout()
plt.show()

print("Number of features/contours:", len(contours))