# -*- coding: utf-8 -*-
"""exp-14

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U21l0Uh8unUwvN2fnXzhNjm0l0NGqdvl
"""

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Use a recently uploaded image path
image_path = 'Screenshot 2026-07-20 143144 (2).png'

img = cv2.imread(image_path)

if img is None:
    print(f"Error: Could not load image from {image_path}. Please make sure the file exists and is accessible.")
else:
    rows, cols = img.shape[:2]

    # Define source and destination points for Homography
    # src_points are the corners of the original image
    src_points = np.float32([[0, 0], [cols - 1, 0], [0, rows - 1], [cols - 1, rows - 1]])

    # dst_points define how the original corners will be mapped, creating a perspective effect
    # This creates a trapezoidal effect where the bottom of the image is narrowed
    dst_points = np.float32([[0, 0], [cols - 1, 0], [0, int(0.7 * rows)], [cols - 1, int(0.7 * rows)]])

    # Find the Homography matrix
    M, _ = cv2.findHomography(src_points, dst_points)

    # Apply the perspective transformation using the homography matrix
    homography_img = cv2.warpPerspective(img, M, (cols, rows))

    # Convert images from BGR to RGB for correct display with matplotlib
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    homography_img_rgb = cv2.cvtColor(homography_img, cv2.COLOR_BGR2RGB)

    # Display the original and transformed images using matplotlib
    plt.figure(figsize=(12, 6))

    plt.subplot(1, 2, 1)
    plt.imshow(img_rgb)
    plt.title('Original Image')
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.imshow(homography_img_rgb)
    plt.title('Homography Transformed Image')
    plt.axis('off')

    plt.show()

    # If you want to save the transformed image, you can uncomment the line below:
    # cv2.imwrite('transformation_using_Homography_Image.jpg', homography_img)