# -*- coding: utf-8 -*-
"""EXP-25

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uOBNRR7WJUTs1aoa_msv7QEc_7skm7qR
"""

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np
import matplotlib.pyplot as plt

filename = list(uploaded.keys())[0]
img = cv2.imread(filename, 0)

# Calculate gradients
gx = cv2.Sobel(img, cv2.CV_64F, 1, 0, ksize=3)
gy = cv2.Sobel(img, cv2.CV_64F, 0, 1, ksize=3)

# Gradient magnitude
gradient = cv2.magnitude(gx, gy)

# Normalize gradient
gradient = cv2.normalize(gradient, None, 0, 255, cv2.NORM_MINMAX)

# Sharpen image
sharp = cv2.addWeighted(img, 1, gradient.astype(np.uint8), 1, 0)

plt.imshow(sharp, cmap='gray')
plt.title('Gradient Masking Sharpening')
plt.axis('off')
plt.show()