# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import cv2
import matplotlib.pyplot as plt

# Load grayscale image
image = cv2.imread("grayscale_image.jpg", cv2.IMREAD_GRAYSCALE)

if image is None:
    print("Image not found!")
    exit()

# 8-bit Quantization (256 Gray Levels)
quantized_8bit = image

# 4-bit Quantization (16 Gray Levels)
quantized_4bit = (image // 16) * 16

# 2-bit Quantization (4 Gray Levels)
quantized_2bit = (image // 64) * 64

# Display Results
plt.figure(figsize=(12,4))

plt.subplot(1,3,1)
plt.imshow(quantized_8bit, cmap='gray')
plt.title("8-bit (256 Gray Levels)")
plt.axis("off")

plt.subplot(1,3,2)
plt.imshow(quantized_4bit, cmap='gray')
plt.title("4-bit (16 Gray Levels)")
plt.axis("off")

plt.subplot(1,3,3)
plt.imshow(quantized_2bit, cmap='gray')
plt.title("2-bit (4 Gray Levels)")
plt.axis("off")

plt.tight_layout()
plt.show()