# -*- coding: utf-8 -*-
"""E-3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_jJZWZM8qGhhUSEPZ4KrL4lr59w50AzJ
"""

import cv2
import matplotlib.pyplot as plt
from google.colab import files

# Upload image
f = files.upload()
img = cv2.imread(list(f.keys())[0], 0)

# Sobel edge detection
sx = cv2.Sobel(img, cv2.CV_64F, 1, 0, ksize=3)
sy = cv2.Sobel(img, cv2.CV_64F, 0, 1, ksize=3)
sobel = cv2.magnitude(sx, sy)

# Canny edge detection
canny = cv2.Canny(img, 100, 200)

# Display results
plt.figure(figsize=(12, 4))

plt.subplot(1, 3, 1)
plt.imshow(img, cmap='gray')
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 3, 2)
plt.imshow(sobel, cmap='gray')
plt.title("Sobel Edge Detection")
plt.axis("off")

plt.subplot(1, 3, 3)
plt.imshow(canny, cmap='gray')
plt.title("Canny Edge Detection")
plt.axis("off")

plt.tight_layout()
plt.show()

# Compare number of detected edge pixels
print("Sobel Edge Pixels :", (sobel > 100).sum())
print("Canny Edge Pixels :", (canny > 0).sum())