# -*- coding: utf-8 -*-
"""EXP-23

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uOBNRR7WJUTs1aoa_msv7QEc_7skm7qR
"""

from google.colab import files
uploaded = files.upload()

import cv2
import matplotlib.pyplot as plt

filename = list(uploaded.keys())[0]
img = cv2.imread(filename, 0)

# Blur the image
blur = cv2.GaussianBlur(img, (5, 5), 0)

# Unsharp masking
sharp = cv2.addWeighted(img, 1.5, blur, -0.5, 0)

plt.imshow(sharp, cmap='gray')
plt.title('Unsharp Masking')
plt.axis('off')
plt.show()