# -*- coding: utf-8 -*-
"""EXP-24

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uOBNRR7WJUTs1aoa_msv7QEc_7skm7qR
"""

from google.colab import files
uploaded = files.upload()

import cv2
import matplotlib.pyplot as plt

filename = list(uploaded.keys())[0]
img = cv2.imread(filename, 0)

# Blur image
blur = cv2.GaussianBlur(img, (5, 5), 0)

# High-Boost filtering
A = 2
sharp = cv2.addWeighted(img, A, blur, -(A - 1), 0)

plt.imshow(sharp, cmap='gray')
plt.title('High-Boost Sharpening')
plt.axis('off')
plt.show()