# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import cv2
import matplotlib.pyplot as plt

# Read grayscale image
image = cv2.imread("medical_image.jpg", cv2.IMREAD_GRAYSCALE)

if image is None:
    print("Image not found!")
    exit()

# -------------------------------
# Simulate Low Pixel Resolution
# -------------------------------
small = cv2.resize(image, (64, 64), interpolation=cv2.INTER_LINEAR)
low_pixel = cv2.resize(small,
                       (image.shape[1], image.shape[0]),
                       interpolation=cv2.INTER_NEAREST)

# -------------------------------
# Simulate Low Intensity Resolution (4-bit)
# -------------------------------
low_intensity = (image // 16) * 16

# -------------------------------
# Display Results
# -------------------------------
plt.figure(figsize=(12,4))

plt.subplot(1,3,1)
plt.imshow(image, cmap='gray')
plt.title("Original Image")
plt.axis("off")

plt.subplot(1,3,2)
plt.imshow(low_pixel, cmap='gray')
plt.title("Low Pixel Resolution")
plt.axis("off")

plt.subplot(1,3,3)
plt.imshow(low_intensity, cmap='gray')
plt.title("Low Intensity Resolution")
plt.axis("off")

plt.tight_layout()
plt.show()