# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import cv2
import matplotlib.pyplot as plt

# Load the image
image = cv2.imread("sample.jpg")

# Check if image is loaded
if image is None:
    print("Error: Image not found.")
else:
    # Convert BGR to RGB
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # Improper Sampling (Reduce Resolution)
    low_sample = cv2.resize(image, (image.shape[1]//4, image.shape[0]//4),
                            interpolation=cv2.INTER_NEAREST)

    # Correct the image using interpolation
    corrected = cv2.resize(low_sample, (image.shape[1], image.shape[0]),
                           interpolation=cv2.INTER_CUBIC)

    # Display Results
    plt.figure(figsize=(12,4))

    plt.subplot(1,3,1)
    plt.imshow(image)
    plt.title("Original Image")
    plt.axis("off")

    plt.subplot(1,3,2)
    plt.imshow(low_sample)
    plt.title("Improper Sampling")
    plt.axis("off")

    plt.subplot(1,3,3)
    plt.imshow(corrected)
    plt.title("Corrected Image")
    plt.axis("off")

    plt.tight_layout()
    plt.show()