# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import cv2
import matplotlib.pyplot as plt

# Load image
image = cv2.imread("sample.jpg")

# Check if image exists
if image is None:
    print("Error: Image not found.")
else:
    # Convert BGR to RGB
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # Simulate Low-Light Condition
    low_light = (image * 0.3).astype("uint8")

    # Convert to grayscale
    gray = cv2.cvtColor(low_light, cv2.COLOR_RGB2GRAY)

    # Enhance image using Histogram Equalization
    enhanced = cv2.equalizeHist(gray)

    # Display results
    plt.figure(figsize=(12,4))

    plt.subplot(1,3,1)
    plt.imshow(image)
    plt.title("Original Image")
    plt.axis("off")

    plt.subplot(1,3,2)
    plt.imshow(low_light)
    plt.title("Low-Light Image")
    plt.axis("off")

    plt.subplot(1,3,3)
    plt.imshow(enhanced, cmap="gray")
    plt.title("Enhanced Image")
    plt.axis("off")

    plt.tight_layout()
    plt.show()