# -*- coding: utf-8 -*-
"""EXP-21

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uOBNRR7WJUTs1aoa_msv7QEc_7skm7qR
"""

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np
import matplotlib.pyplot as plt

filename = list(uploaded.keys())[0]
img = cv2.imread(filename, 0)

# Laplacian mask with diagonal neighbors
mask = np.array([
    [-1, -1, -1],
    [-1,  8, -1],
    [-1, -1, -1]
], dtype=np.float32)

lap = cv2.filter2D(img, cv2.CV_32F, mask)

# Sharpen image
sharp = cv2.addWeighted(img.astype(np.float32), 1, lap, 1, 0)
sharp = np.clip(sharp, 0, 255).astype(np.uint8)

plt.imshow(sharp, cmap='gray')
plt.title('Laplacian Sharpened Image')
plt.axis('off')
plt.show()