# -*- coding: utf-8 -*-
"""E-1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_jJZWZM8qGhhUSEPZ4KrL4lr59w50AzJ
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Upload image
uploaded = files.upload()
img = cv2.imread(list(uploaded.keys())[0], 0)

# Add Gaussian noise
noise = np.random.normal(0, 25, img.shape)
noisy = np.clip(img + noise, 0, 255).astype(np.uint8)

# Noise removal
median = cv2.medianBlur(noisy, 5)
gaussian = cv2.GaussianBlur(noisy, (5,5), 0)

# Normalization
normalized = cv2.normalize(median, None, 0, 255, cv2.NORM_MINMAX)

# Feature detection using Canny
edge_original = cv2.Canny(img, 100, 200)
edge_noisy = cv2.Canny(noisy, 100, 200)
edge_median = cv2.Canny(median, 100, 200)
edge_normalized = cv2.Canny(normalized, 100, 200)

# Display results
images = [img, noisy, median, gaussian, normalized,
          edge_original, edge_noisy, edge_median, edge_normalized]

titles = ["Original", "Noisy", "Median Filter", "Gaussian Filter",
          "Normalized", "Original Edges", "Noisy Edges",
          "Median Edges", "Normalized Edges"]

plt.figure(figsize=(12,8))

for i in range(9):
    plt.subplot(3,3,i+1)
    plt.imshow(images[i], cmap='gray')
    plt.title(titles[i])
    plt.axis('off')

plt.tight_layout()
plt.show()

# Edge density calculation
def edge_density(edge):
    return np.sum(edge > 0) / edge.size

print("Edge Density:")
print("Original     :", round(edge_density(edge_original), 4))
print("Noisy        :", round(edge_density(edge_noisy), 4))
print("Median Filter:", round(edge_density(edge_median), 4))
print("Normalized   :", round(edge_density(edge_normalized), 4))