# -*- coding: utf-8 -*-
"""E-5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_jJZWZM8qGhhUSEPZ4KrL4lr59w50AzJ
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Upload image
f = files.upload()
img = cv2.imread(list(f.keys())[0], 0)

# Add Gaussian noise
noise = np.random.normal(0, 30, img.shape)
noisy = np.clip(img + noise, 0, 255).astype(np.uint8)

# Gaussian filtering to reduce noise
filtered = cv2.GaussianBlur(noisy, (5, 5), 0)

# Harris corner detection function
def harris(image):
    x = np.float32(image)
    corners = cv2.cornerHarris(x, 2, 3, 0.04)
    result = cv2.cvtColor(image, cv2.COLOR_GRAY2RGB)
    result[corners > 0.01 * corners.max()] = [255, 0, 0]
    return result, corners

# Detect corners
original, c1 = harris(img)
noisy_img, c2 = harris(noisy)
filtered_img, c3 = harris(filtered)

# Display results
plt.figure(figsize=(12, 4))

for i, (im, title) in enumerate([
    (original, "Original + Harris"),
    (noisy_img, "Noisy + Harris"),
    (filtered_img, "Filtered + Harris")
]):
    plt.subplot(1, 3, i + 1)
    plt.imshow(im)
    plt.title(title)
    plt.axis("off")

plt.tight_layout()
plt.show()

# Number of detected corners
print("Original corners :", np.sum(c1 > 0.01 * c1.max()))
print("Noisy corners    :", np.sum(c2 > 0.01 * c2.max()))
print("Filtered corners :", np.sum(c3 > 0.01 * c3.max()))