# -*- coding: utf-8 -*-
"""EXP-17

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uOBNRR7WJUTs1aoa_msv7QEc_7skm7qR
"""

from google.colab import files
uploaded = files.upload()

import cv2
import matplotlib.pyplot as plt

# Try loading the image without forcing grayscale first
img_color = cv2.imread('/content/Screenshot 2026-07-20 143144 (1).png')

if img_color is None:
    print("Error: Could not load image from the specified path.")
else:
    # Convert to grayscale if it's a color image
    if len(img_color.shape) == 3:
        img = cv2.cvtColor(img_color, cv2.COLOR_BGR2GRAY)
    else: # Already grayscale or 1-channel
        img = img_color

    sobel_x = cv2.Sobel(img, cv2.CV_64F, 1, 0, ksize=3)

    plt.imshow(abs(sobel_x), cmap='gray')
    plt.title('Sobel Edge Detection - X Axis')
    plt.axis('off')
    plt.show()