# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import cv2
import matplotlib.pyplot as plt

# Load image (replace with your autonomous driving image)
image = cv2.imread("road.jpg")

if image is None:
    print("Image not found!")
    exit()

# Convert BGR to RGB
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Image Formation Model Improvements

# 1. Noise Reduction
denoised = cv2.GaussianBlur(image_rgb, (5, 5), 0)

# 2. Contrast Enhancement
gray = cv2.cvtColor(denoised, cv2.COLOR_RGB2GRAY)
equalized = cv2.equalizeHist(gray)

# 3. Edge Detection
edges = cv2.Canny(equalized, 100, 200)

# Display Results
plt.figure(figsize=(12,8))

plt.subplot(2,2,1)
plt.imshow(image_rgb)
plt.title("Original Image")
plt.axis("off")

plt.subplot(2,2,2)
plt.imshow(denoised)
plt.title("Noise Reduced")
plt.axis("off")

plt.subplot(2,2,3)
plt.imshow(equalized, cmap="gray")
plt.title("Contrast Enhanced")
plt.axis("off")

plt.subplot(2,2,4)
plt.imshow(edges, cmap="gray")
plt.title("Edge Detection")
plt.axis("off")

plt.tight_layout()
plt.show()