# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import cv2
import matplotlib.pyplot as plt

# Load image
image = cv2.imread("sample.jpg")

# Check if image exists
if image is None:
    print("Error: Image not found.")
else:
    # Convert BGR to RGB
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # Create aliasing by downsampling without filtering
    aliased = cv2.resize(image, (image.shape[1]//4, image.shape[0]//4),
                         interpolation=cv2.INTER_NEAREST)

    aliased = cv2.resize(aliased, (image.shape[1], image.shape[0]),
                         interpolation=cv2.INTER_NEAREST)

    # Corrective approach: Apply Gaussian Blur before resizing
    blurred = cv2.GaussianBlur(image, (5, 5), 0)

    corrected = cv2.resize(blurred, (image.shape[1]//4, image.shape[0]//4),
                           interpolation=cv2.INTER_AREA)

    corrected = cv2.resize(corrected, (image.shape[1], image.shape[0]),
                           interpolation=cv2.INTER_CUBIC)

    # Display images
    plt.figure(figsize=(12,4))

    plt.subplot(1,3,1)
    plt.imshow(image)
    plt.title("Original Image")
    plt.axis("off")

    plt.subplot(1,3,2)
    plt.imshow(aliased)
    plt.title("Aliased Image")
    plt.axis("off")

    plt.subplot(1,3,3)
    plt.imshow(corrected)
    plt.title("Corrected Image")
    plt.axis("off")

    plt.tight_layout()
    plt.show()