# -*- coding: utf-8 -*-
"""exp-10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U21l0Uh8unUwvN2fnXzhNjm0l0NGqdvl
"""

from google.colab import files
uploaded = files.upload()

import cv2
import matplotlib.pyplot as plt

# Using the image uploaded to Colab
image_path = 'Screenshot 2026-07-20 143144 (1).png'

image = cv2.imread(image_path)

if image is None:
    print(f"Error: Could not load image from {image_path}. Please make sure the file exists and is accessible.")
else:
    # Convert BGR (OpenCV default) to RGB (Matplotlib default) for correct color display
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    plt.figure(figsize=(8, 6))
    plt.imshow(image_rgb)
    plt.title('Original Image')
    plt.axis('off') # Hide axes for cleaner image display
    plt.show()