# -*- coding: utf-8 -*-
"""exp-9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U21l0Uh8unUwvN2fnXzhNjm0l0NGqdvl
"""

from google.colab import files
uploaded = files.upload()

import cv2
import matplotlib.pyplot as plt

image_path = 'Screenshot 2026-07-13 142020.png' # Using the image you just uploaded

img = cv2.imread(image_path)

if img is None:
    print(f"Error: Could not load image from {image_path}. Please make sure the file exists and is accessible.")
else:
    # Convert BGR to RGB for displaying with matplotlib
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # Rotate clockwise
    rotated_img_clockwise = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)
    rotated_img_clockwise_rgb = cv2.cvtColor(rotated_img_clockwise, cv2.COLOR_BGR2RGB)

    # Rotate counterclockwise
    rotated_img_counterclockwise = cv2.rotate(img, cv2.ROTATE_90_COUNTERCLOCKWISE)
    rotated_img_counterclockwise_rgb = cv2.cvtColor(rotated_img_counterclockwise, cv2.COLOR_BGR2RGB)

    plt.figure(figsize=(15, 5))

    plt.subplot(1, 3, 1)
    plt.imshow(img_rgb)
    plt.title('Original Image')
    plt.axis('off')

    plt.subplot(1, 3, 2)
    plt.imshow(rotated_img_clockwise_rgb)
    plt.title('Rotated 90° Clockwise')
    plt.axis('off')

    plt.subplot(1, 3, 3)
    plt.imshow(rotated_img_counterclockwise_rgb)
    plt.title('Rotated 90° Counterclockwise')
    plt.axis('off')

    plt.show()

# No need for cv2.imwrite unless you specifically want to save it to disk