# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import cv2
import matplotlib.pyplot as plt

# Load noisy image
image = cv2.imread("noisy_image.jpg")

if image is None:
    print("Image not found!")
    exit()

# Convert BGR to RGB
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Noise Reduction using Gaussian Blur
gaussian = cv2.GaussianBlur(image, (5, 5), 0)

# Noise Reduction using Median Filter
median = cv2.medianBlur(image, 5)

# Display Images
plt.figure(figsize=(12,4))

plt.subplot(1,3,1)
plt.imshow(image)
plt.title("Original Noisy Image")
plt.axis("off")

plt.subplot(1,3,2)
plt.imshow(gaussian)
plt.title("Gaussian Filter")
plt.axis("off")

plt.subplot(1,3,3)
plt.imshow(median)
plt.title("Median Filter")
plt.axis("off")

plt.tight_layout()
plt.show()