# -*- coding: utf-8 -*-
"""exp-15

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U21l0Uh8unUwvN2fnXzhNjm0l0NGqdvl
"""

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np

src = np.float32([[0,0], [100,0], [100,100], [0,100]])
dst = np.float32([[10,20], [120,10], [110,120], [20,110]])

# Find DLT transformation matrix
H, _ = cv2.findHomography(src, dst)

print("DLT Matrix:")
print(H)

# Transform points
points = src.reshape(-1, 1, 2)
result = cv2.perspectiveTransform(points, H)

print("Transformed Points:")
print(result.reshape(-1, 2))