# -*- coding: utf-8 -*-
"""EXP-22

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uOBNRR7WJUTs1aoa_msv7QEc_7skm7qR
"""

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np
import matplotlib.pyplot as plt

filename = list(uploaded.keys())[0]
img = cv2.imread(filename, 0)

# Laplacian mask with positive center
mask = np.array([
    [0, -1, 0],
    [-1, 5, -1],
    [0, -1, 0]
], dtype=np.float32)

sharp = cv2.filter2D(img, -1, mask)

plt.imshow(sharp, cmap='gray')
plt.title('Laplacian Sharpened Image')
plt.axis('off')
plt.show()