# -*- coding: utf-8 -*-
"""exp-12

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U21l0Uh8unUwvN2fnXzhNjm0l0NGqdvl
"""

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Use one of the uploaded image paths
image_path = 'Screenshot 2026-07-13 142020 (1).png'

img = cv2.imread(image_path)

if img is None:
    print(f"Error: Could not load image from {image_path}. Please make sure the file exists and is accessible.")
else:
    rows, cols = img.shape[:2]

    # Define source and destination points for perspective transformation
    src_points = np.float32([[0, 0], [cols - 1, 0], [0, rows - 1], [cols - 1, rows - 1]])
    # These destination points create a trapezoidal distortion
    dst_points = np.float32([[0, 0], [cols - 1, 0], [int(0.33 * cols), rows - 1], [int(0.66 * cols), rows - 1]])

    # Get the perspective transformation matrix
    M = cv2.getPerspectiveTransform(src_points, dst_points)

    # Apply the perspective transformation
    perspective_img = cv2.warpPerspective(img, M, (cols, rows))

    # Convert images from BGR to RGB for correct display with matplotlib
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    perspective_img_rgb = cv2.cvtColor(perspective_img, cv2.COLOR_BGR2RGB)

    # Display the original and transformed images using matplotlib
    plt.figure(figsize=(12, 6))

    plt.subplot(1, 2, 1)
    plt.imshow(img_rgb)
    plt.title('Original Image')
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.imshow(perspective_img_rgb)
    plt.title('Perspective Transformed Image')
    plt.axis('off')

    plt.show()

    # If you still want to save the transformed image to disk, uncomment the line below:
    # cv2.imwrite('Perspective_Transformed_Image.jpg', perspective_img)