# -*- coding: utf-8 -*-
"""EXP-20

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uOBNRR7WJUTs1aoa_msv7QEc_7skm7qR
"""

from google.colab import files
uploaded = files.upload()

import cv2
import matplotlib.pyplot as plt

filename = list(uploaded.keys())[0]
img = cv2.imread(filename, 0)

sobel_x = cv2.Sobel(img, cv2.CV_64F, 1, 0, ksize=3)
sobel_y = cv2.Sobel(img, cv2.CV_64F, 0, 1, ksize=3)

sobel_xy = cv2.magnitude(sobel_x, sobel_y)

plt.imshow(sobel_xy, cmap='gray')
plt.title('Sobel XY Edge Detection')
plt.axis('off')
plt.show()