# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import cv2
import matplotlib.pyplot as plt

# Load image
image = cv2.imread("image.jpg")

# Check if the image was loaded successfully
if image is None:
    print("Error: 'image.jpg' not found. Please upload the image or check the file path.")
    exit() # Exit to prevent further errors if image is not loaded

image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Create a low-resolution version
low_res = cv2.resize(image, (64, 64), interpolation=cv2.INTER_LINEAR)

# Scale back to original size for display
restored = cv2.resize(low_res, (image.shape[1], image.shape[0]),
                      interpolation=cv2.INTER_NEAREST)

# Display images
plt.figure(figsize=(10,5))

plt.subplot(1,2,1)
plt.imshow(image)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1,2,2)
plt.imshow(restored)
plt.title("Low Resolution Image")
plt.axis("off")

plt.show()