# -*- coding: utf-8 -*-
"""EXP-16

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uOBNRR7WJUTs1aoa_msv7QEc_7skm7qR
"""

from google.colab import files
uploaded = files.upload()

import cv2
import matplotlib.pyplot as plt

img = cv2.imread('/content/Screenshot 2026-07-13 142020.png', 0)

edges = cv2.Canny(img, 100, 200)

plt.imshow(edges, cmap='gray')
plt.title('Canny Edge Detection')
plt.axis('off')
plt.show()