# -*- coding: utf-8 -*-
"""E-4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_jJZWZM8qGhhUSEPZ4KrL4lr59w50AzJ
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Upload image
f = files.upload()
img = cv2.imread(list(f.keys())[0])

# Convert to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Harris corner detection
gray = np.float32(gray)
corners = cv2.cornerHarris(gray, 2, 3, 0.04)

# Mark strong corners
result = img.copy()
result[corners > 0.01 * corners.max()] = [0, 0, 255]

# Display
plt.figure(figsize=(10, 4))

plt.subplot(1, 2, 1)
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(cv2.cvtColor(result, cv2.COLOR_BGR2RGB))
plt.title("Harris Corners")
plt.axis("off")

plt.show()

# Number of detected corners
print("Number of corners:",
      np.sum(corners > 0.01 * corners.max()))